### ISSUE TITLE
Behave correctly with cache and apt-get

### ISSUE THREAD

**Issue by pescetti** [andrewholgate/docker-drupal-php70-dev#7]
### Scope

Build is often broken. One of the causes is that the `Dockerfile` structure does not work well with the Docker cache.
### Description
- On one hand, Docker caches each stage with a _time-independent_ approach: if container is in state _X_ (corresponding to a hash) and command _C_ brings the container in state _Y_ (corresponding to another hash) then Docker caches this information and will reuse it whenever possible.
- On the other hand, this assumption is wrong for some commands that happen to be _time-dependent_: running `apt-get install mypackage` last week or today results in different end states if a newer version of `mypackage` is available.
### Solutions
1. Do all `apt-get` commands at once. Example: https://github.com/coderstephen/dockerfiles/blob/master/php7/Dockerfile
2. Always run an `apt-get update` before any `apt-get install` to minimize the risk of a broken build due to stale data. Example: https://github.com/docker-library/php/blob/7bd5c38db974ee629a815896add1ec568a1cc88c/7.0/fpm/Dockerfile (note line 4 and 7) or, applied to this project, something like this: https://github.com/pescetti/docker-drupal-php70-dev/commit/66997622f4b04476dc7ba2178dad10b1b40fd3f6

Main disadvantage of 1: if you want to add a package, you need a full rebuild and you invalidate all your cache.
Main disadvantage of 2: it is more verbose and is not immediately understandable why one is doing it.

**Comment by andrewholgate** [comment]
I feel it's an an acceptable solution to use `--no-cache` when building it in order to avoid this issue.

This Docker container is fairly mature now so the need to make changes and rebuild it are fairly rare. The additional time to rebuild with `--no-cache` on these occasions is acceptable.

**Comment by pescetti** [comment]
With so many downloads involved and occasional server issues (which I did encounter rebuilding several times), cache can be useful also in terms of reliability.

If the container is fairly mature, then I would recommend to go for option 1 (all `apt-get install` calls in one command) to avoid rebuild issues.

At the very least, if no changes are made, then `README.md` should simply contain the recommendation to use `--no-cache` when rebuilding, since the default settings will make the build possibly inconsistent.
